#!/bin/bash


_hell_zip () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "Extended" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL01hZE1heDM5My9FeHRlbmRlZFBsdWdpbi9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $UPSTREAM_REPO == "Original" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1NYWRNYXgvUGx1Z2luL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL01hZE1heDM5My9FeHRlbmRlZFBsdWdpbi9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}

_library () {
    if [[ $BOT_LIBRARY == "pyrogram" ]]
    then 
        python3 -m PyrogramHell
    else
        python3 -m TelethonHell
    fi
}

_starter () {
    local hellpath
    hellpath="Plugins.zip"
    echo "••• DOWNLOADING HELLBOT •••"
    wget -q $(_hell_zip) -O "$hellpath"
    HELLPATH=$(zipinfo -1 "$hellpath" | grep -v "/.");
    unzip -qq "$hellpath"
    rm -rf "$hellpath"
    cd $HELLPATH
    python3 ../updater.py ../requirements.txt requirements.txt
    echo "••• STARTING HELLBOT •••"
    _library
}

_starter
